#!/bin/sh

REPOURL='http://httpredir.debian.org/debian'
CODENAME=`lsb_release -cs`
SECTION='main contrib non-free'

cat <<DATA > /etc/apt/sources.list
deb $REPOURL $CODENAME $SECTION
deb-src $REPOURL $CODENAME $SECTION

deb http://security.debian.org/ $CODENAME/updates $SECTION
deb-src http://security.debian.org/ $CODENAME/updates $SECTION

deb $REPOURL $CODENAME-updates $SECTION
deb-src $REPOURL $CODENAME-updates $SECTION

deb $REPOURL $CODENAME-backports $SECTION
deb-src $REPOURL $CODENAME-backports $SECTION
DATA

cat <<DATA > /etc/apt/preferences
Package: *
Pin: release n=$CODENAME-backports
Pin-Priority: 992

Package: *
Pin: release n=$CODENAME-updates
Pin-Priority: 995
DATA

echo linux-image-amd64 hold | dpkg --set-selections
apt-get update -y
