#!/bin/sh

apt-get install -y build-essential automake gettext re2c pkg-config \
        libxml2-dev libssl-dev libbz2-dev libsqlite3-dev \
        libpng12-dev libjpeg-dev libmcrypt-dev libtidy-dev \
        libxslt1-dev libpcre3-dev liblzma-dev unixodbc-dev
