#!/bin/sh

COMPOSE_VERSION=1.5.2
MACHINE_VERSION=v0.5.6

# https://github.com/docker/compose/releases/
COMPOSE_URL=https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-Linux-x86_64
COMPOSE_PATH=/usr/local/bin/docker-compose
COMPOSE_CACHE=/vagrant/.cache/docker-compose-Linux-x86_64-$COMPOSE_VERSION
if [ ! -f $COMPOSE_CACHE ]; then
  curl -sSL $COMPOSE_URL > $COMPOSE_CACHE
fi
cp $COMPOSE_CACHE $COMPOSE_PATH
chmod +x $COMPOSE_PATH

# https://github.com/docker/machine/releases
MACHINE_URL=https://github.com/docker/machine/releases/download/$MACHINE_VERSION/docker-machine_linux-amd64
MACHINE_PATH=/usr/local/bin/docker-machine
MACHINE_CACHE=/vagrant/.cache/docker-machine_linux-amd64-$MACHINE_VERSION
if [ ! -f $MACHINE_CACHE ]; then
  curl -sSL $MACHINE_URL > $MACHINE_CACHE
fi
cp $MACHINE_CACHE $MACHINE_PATH
chmod +x $MACHINE_PATH
