#!/bin/sh

# able to chsh without password
cat <<'DATA' > /etc/pam.d/chsh
auth     required   pam_shells.so
auth     sufficient pam_rootok.so
@include common-account
@include common-session
DATA

cat <<'DATA' > /etc/locale.gen
en_US.UTF-8 UTF-8
ja_JP.EUC-JP EUC-JP
ja_JP.UTF-8 UTF-8
DATA
locale-gen

localectl set-keymap jp106


cat <<'DATA' > /etc/rc.local
#!/bin/sh -e

# network speed tuning
echo ffff > /sys/class/net/eth0/queues/rx-0/rps_cpus
echo ffff > /sys/class/net/eth0/queues/tx-0/xps_cpus
echo 32768 > /sys/class/net/eth0/queues/rx-0/rps_flow_cnt

echo ffff > /sys/class/net/eth1/queues/rx-0/rps_cpus
echo ffff > /sys/class/net/eth1/queues/tx-0/xps_cpus
echo 32768 > /sys/class/net/eth1/queues/rx-0/rps_flow_cnt

echo 32768 > /proc/sys/net/core/rps_sock_flow_entries

exit 0
DATA
chmod +x /etc/rc.local
systemctl restart rc-local.service
