#!/bin/sh

# able to chsh without password
cat <<'DATA' > /etc/pam.d/chsh
auth     required   pam_shells.so
auth     sufficient pam_rootok.so
@include common-account
@include common-session
DATA

cat <<'DATA' > /etc/locale.gen
en_US.UTF-8 UTF-8
ja_JP.EUC-JP EUC-JP
ja_JP.UTF-8 UTF-8
DATA
locale-gen
