# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_version = ENV['LATEST_BOX_VERSION'] || "8.2.1"
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  repourl='http://httpredir.debian.org/debian'
  codename='jessie'
  section='main contrib non-free'

  sources_list = <<-HERE.gsub(/^ +/, '')
    deb #{repourl} #{codename} #{section}
    deb-src #{repourl} #{codename} #{section}

    deb http://security.debian.org/ #{codename}/updates #{section}
    deb-src http://security.debian.org/ #{codename}/updates #{section}

    deb #{repourl} #{codename}-updates #{section}
    deb-src #{repourl} #{codename}-updates #{section}

    deb #{repourl} #{codename}-backports #{section}
    deb-src #{repourl} #{codename}-backports #{section}
  HERE

  preferences = <<-HERE.gsub(/^ +/, '')
    Package: *
    Pin: release n=#{codename}-backports
    Pin-Priority: 992

    Package: *
    Pin: release n=#{codename}-updates
    Pin-Priority: 995
  HERE

  cleanup = <<-'HERE'.gsub(/^ +/, '')
    echo '\033[1;33mCleanup\033[0;39m'
    echo -n '\033[0;33m'
    old_kernels=\$(dpkg -l | egrep 'linux-(image|headers)-[0-9]' | grep -v \$(uname -r | sed s/-amd64//) | awk '{print \$2}')
    if [ x\$old_kernels != x ]; then
      apt-get -y purge \$old_kernels
      apt-get -y autoremove
      apt-get clean
    fi
    dd if=/dev/zero of=zero bs=1MiB
    rm zero
    echo -n '\033[0;39m'
  HERE

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    echo "#{sources_list}" > /etc/apt/sources.list
    echo "#{preferences}" > /etc/apt/preferences
    echo "#{cleanup}" > /cleanup
    apt-get -y update
    apt-get -y upgrade
    apt-get -y dist-upgrade
    apt-get -y install linux-headers-amd64 virtualbox-guest-dkms
    apt-get -y autoremove
    apt-get clean
  SHELL
end
