# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.ssh.insert_key = false

  config.vm.box = ENV['LATEST_BOX'] || "debian/contrib-jessie64"
  config.vm.box_version = ENV['LATEST_BOX'] ? "0" : "8.5.2"
  config.vm.box_check_update = true
  config.vm.hostname = "debian8"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile
  SHELL

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973" ]
    vb.linked_clone = ENV['LATEST_BOX'] ? true : false
  end

  repourl='http://httpredir.debian.org/debian'
  codename='jessie'
  section='main contrib non-free'

  sources_list = <<-HERE.gsub(/^ +/, '')
    deb #{repourl} #{codename} #{section}
    deb-src #{repourl} #{codename} #{section}

    deb http://security.debian.org/ #{codename}/updates #{section}
    deb-src http://security.debian.org/ #{codename}/updates #{section}

    deb #{repourl} #{codename}-updates #{section}
    deb-src #{repourl} #{codename}-updates #{section}

    deb #{repourl} #{codename}-backports #{section}
    deb-src #{repourl} #{codename}-backports #{section}
  HERE

  preferences = <<-HERE.gsub(/^ +/, '')
    Package: *
    Pin: release n=#{codename}-backports
    Pin-Priority: 992

    Package: *
    Pin: release n=#{codename}-updates
    Pin-Priority: 995
  HERE

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    export LANG=en_US.utf8
    echo "#{sources_list}" > /etc/apt/sources.list
    echo "#{preferences}" > /etc/apt/preferences
    apt-get -y update
    apt-get -y dist-upgrade
    apt-get -y install linux-headers-amd64 virtualbox-guest-dkms
    /vagrant/system.sh
    /vagrant/packages.sh
    /vagrant/git.sh
    /vagrant/ag.sh
    /vagrant/peco.sh
    /vagrant/jo.sh
    /vagrant/docker.sh
    apt-get -y autoremove --purge
    readlink /var/cache/apt/archives || apt-get clean
    echo "Finish provisioning"
  SHELL
end
